// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALMLBVqsp53Kn8TNexIm5AKAlApi5aU4s',
    appId: '1:712002654833:android:f1ba749ff64763fa7dc1d0',
    messagingSenderId: '712002654833',
    projectId: 'nephro-care-5f88e',
    storageBucket: 'nephro-care-5f88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNVOnnQzNbnzul1GAcAuxgV1LTUJBw9q8',
    appId: '1:712002654833:ios:e72ed59fa5c7a0797dc1d0',
    messagingSenderId: '712002654833',
    projectId: 'nephro-care-5f88e',
    storageBucket: 'nephro-care-5f88e.firebasestorage.app',
    androidClientId: '712002654833-nof86q3bhbm7eg56dfg4vtfuhm1kg704.apps.googleusercontent.com',
    iosClientId: '712002654833-0qfmml7fnt555aretnlogbmahc3tfqnt.apps.googleusercontent.com',
    iosBundleId: 'com.nephrocare.nephroCare',
  );

}